title: Cheat sheet for a perfect movie
description: Data Story For A Perfect Movie
show_downloads: True

theme: jekyll-theme-cayman

navigation:
  - title: Home
    url: /
  - title : Example
    url : example
