theme: jekyll-theme-cayman
title: Cheat sheet for a perfect movie
description: Data Story For A Perfect Movie
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
