theme: jekyll-theme-minimal
title: Cheat Sheet For A Perfect Movie
description: By Victoria, Anna, Camille, Asama, Ilyaas
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
