remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "Cheat Sheet For A Perfect Movie"
description: By Victoria, Anna, Camille, Asama, Ilyaas
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
