title: BLABLA Cheat sheet for a perfect movie LALA
description: Data Story For A Perfect Movie
show_downloads: True

theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

navigation:
  - title: Home
    url: /
