title: Cheat sheet for a perfect movie
description: Data Story For A Perfect Movie
show_downloads: True

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

navigation:
  - title: Home
    url: /
  - title: Example
    url: example
