theme: jekyll-theme-minimal
title: Cheat sheet for a perfect movie
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
